name: 'dbt_scooters_new'
version: '1.0.0'

profile: 'dbt_scooters_new'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
    - "grant usage on schema dbt_finance to finance;"

models:
  dbt_scooters_new:
    +materialized: table
    +on_schema_change: append_new_columns
    +persist_docs:
      relation: true
      columns: true
    finance:
      +schema: "finance"
seeds:
  dbt_scooters_new:
    +persist_docs:
      relation: true
      columns: true
      
vars:
  'dbt_date:time_zone': 'Europe/Moscow'